<?php

/**
 * Copyright © Klevu Oy. All rights reserved. See LICENSE.txt for license details.
 */

declare(strict_types=1);

use Klevu\FrontendRecommendations\Block\Widget\Recommendations;

/**
 * @var Recommendations $block
 */
$title = trim($block->escapeHtml($block->getData('klevu_recs_title')));
$isDynamicBlock = (bool)$block->getData('klevu_dynamic_block');
$recsId = $block->escapeHtml($block->getData('klevu_recs_id'));
?>
<div class="klevu-recs-container">
    <?php if (/*@noEscape*/ $title): ?>
        <div>
            <strong>
                <?= /*@noEscape*/ $title ?>
            </strong>
        </div>
    <?php endif; ?>
    <?php if (/*@noEscape*/ $isDynamicBlock): ?>
        <div class="klevu-recs"
             id="<?= /*@noEscape*/ $recsId ?>"
             data-bind="afterRender: function(recsTargetElement) {
                if ('undefined' !== typeof klevu && 'undefined' === typeof recsTargetElement.recsObject) {
                    let myRecsbox = klevu.recs.clone({
                        recId: recsTargetElement.id,
                        apiKey: klevu.getGlobalSetting('recs.apiKey', klevu.getGlobalSetting('global.apiKey')),
                        element: recsTargetElement
                    });
                    myRecsbox.powerUp();
                }
            }">
        </div>
    <?php else: ?>
        <div class="klevu-recs" id="<?= /*@noEscape*/ $recsId ?>"></div>
    <?php endif; ?>
</div>
