<?php

/**
 * Copyright © Klevu Oy. All rights reserved. See LICENSE.txt for license details.
 */

declare(strict_types=1);

use Klevu\FrontendRecommendations\Block\Widget\Recommendations;
use Magento\Framework\Escaper;

/**
 * @var Recommendations $block
 * @var Escaper $escaper
 */
$title = trim($block->getData('klevu_recs_title') ?? '');
$isDynamicBlock = (bool)$block->getData('klevu_dynamic_block');
$recsId = $block->getData('klevu_recs_id');
?>

<?php if ($recsId): ?>
    <div class="klevu-recs-container">
        <?php if ($title): ?>
            <div>
                <strong>
                    <?= $escaper->escapeHtml($title) ?>
                </strong>
            </div>
        <?php endif; ?>
        <?php if ($isDynamicBlock): ?>
            <div class="klevu-recs"
                 id="<?= $escaper->escapeHtmlAttr($recsId) ?>"
                 data-bind="afterRender: function(recsTargetElement) {
                    if ('undefined' !== typeof klevu && 'undefined' === typeof recsTargetElement.recsObject) {
                        let myRecsbox = klevu.recs.clone({
                            recId: recsTargetElement.id,
                            apiKey: klevu.getGlobalSetting('recs.apiKey', klevu.getGlobalSetting('global.apiKey')),
                            element: recsTargetElement
                        });
                        myRecsbox.powerUp();
                    }
                }">
            </div>
        <?php else: ?>
            <div class="klevu-recs" id="<?= $escaper->escapeHtmlAttr($recsId) ?>"></div>
        <?php endif; ?>
    </div>
<?php endif; ?>
